name: "Build and push container image"


on:
  push:
    branches: ["*"]
    tags: ["*"]
  schedule:
    - cron: "0 0 * * *"


jobs:
  main:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Login to Docker Hub"
        uses: "docker/login-action@v3"
        with:
          registry: "docker.io"
          username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          password: "${{ secrets.DOCKER_HUB_PASSWORD }}"

      - name: "Login to RedHat Quay"
        uses: "docker/login-action@v3"
        with:
          registry: "quay.io"
          username: "${{ secrets.REDHAT_QUAY_USERNAME }}"
          password: "${{ secrets.REDHAT_QUAY_PASSWORD }}"

      - name: "Set up QEMU"
        uses: "docker/setup-qemu-action@v3"

      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@v3"

      - name: "Build and push"
        uses: "docker/build-push-action@v6"
        with:
          platforms: "linux/amd64"
          push: true
          tags: |
            docker.io/${{ github.repository }}:latest
            docker.io/${{ github.repository }}:${{ github.ref_name }}
            quay.io/${{ github.repository }}:latest
            quay.io/${{ github.repository }}:${{ github.ref_name }}
